/**
 * @fileOverview Base de Dados Inicial e Mock Data para o Agendador de ASOs + Kits de Clínicas (NAI)
 */

import { PartnerClinic, AsoRequest, AsoPipelineStep, ExamType } from "@/types/aso-scheduler-types";

export const INITIAL_PARTNER_CLINICS: PartnerClinic[] = [
  {
    id: "CLIN_01",
    name: "Centro de Medicina Ocupacional Paulista",
    cnpj: "11.222.333/0001-44",
    address: "Av. Paulista, 1500 - Bela Vista",
    neighborhood: "Bela Vista",
    city: "São Paulo",
    state: "SP",
    distanceKm: 2.4,
    rating: 4.9,
    priceCategory: "STANDARD",
    turnaroundTimeDays: 1,
    supportedExams: [
      "Avaliação Clínica",
      "Audiometria",
      "Espirometria",
      "RX Tórax OIT",
      "ECG",
      "EEG",
      "Acuidade Visual",
      "Glicemia",
      "Hemograma",
    ],
    availableTimeSlots: ["08:00", "09:30", "11:00", "13:30", "15:00"],
    contactPhone: "(11) 3254-8800",
    contactEmail: "agendamento@paulistaocupacional.com.br",
    performanceScore: 98,
  },
  {
    id: "CLIN_02",
    name: "Ambulatório & Saúde Ocupacional Pinheiros",
    cnpj: "22.333.444/0001-55",
    address: "Rua Funchal, 418 - Vila Olímpia",
    neighborhood: "Vila Olímpia",
    city: "São Paulo",
    state: "SP",
    distanceKm: 4.8,
    rating: 4.7,
    priceCategory: "ECONOMIC",
    turnaroundTimeDays: 2,
    supportedExams: [
      "Avaliação Clínica",
      "Audiometria",
      "Espirometria",
      "ECG",
      "Acuidade Visual",
      "Glicemia",
      "Avaliação Psicotécnica",
    ],
    availableTimeSlots: ["08:30", "10:00", "14:00", "16:00"],
    contactPhone: "(11) 3845-9922",
    contactEmail: "convenios@saudepinheiros.com.br",
    performanceScore: 92,
  },
  {
    id: "CLIN_03",
    name: "Instituto de Ergonomia & Medicina do Trabalho Alphaville",
    cnpj: "33.444.555/0001-66",
    address: "Alameda Rio Negro, 500 - Alphaville",
    neighborhood: "Alphaville",
    city: "Barueri",
    state: "SP",
    distanceKm: 18.2,
    rating: 4.95,
    priceCategory: "PREMIUM",
    turnaroundTimeDays: 1,
    supportedExams: [
      "Avaliação Clínica",
      "Audiometria",
      "Espirometria",
      "RX Tórax OIT",
      "ECG",
      "EEG",
      "Acuidade Visual",
      "Glicemia",
      "Avaliação Psicotécnica",
      "Toxicológico",
    ],
    availableTimeSlots: ["07:30", "09:00", "10:30", "13:00", "14:30"],
    contactPhone: "(11) 4195-1100",
    contactEmail: "atendimento@alphavillemed.com.br",
    performanceScore: 99,
  },
  {
    id: "CLIN_04",
    name: "Clínica Integrada de SST ABC",
    cnpj: "44.555.666/0001-77",
    address: "Av. Industrial, 780 - Bairro Jardim",
    neighborhood: "Bairro Jardim",
    city: "Santo André",
    state: "SP",
    distanceKm: 12.5,
    rating: 4.6,
    priceCategory: "ECONOMIC",
    turnaroundTimeDays: 2,
    supportedExams: [
      "Avaliação Clínica",
      "Audiometria",
      "Espirometria",
      "RX Tórax OIT",
      "ECG",
      "Glicemia",
    ],
    availableTimeSlots: ["08:00", "10:00", "13:30", "15:30"],
    contactPhone: "(11) 4438-5500",
    contactEmail: "recepcao@sstabc.com.br",
    performanceScore: 89,
  },
];

export const PIPELINE_STEPS_CONFIG: Record<
  AsoPipelineStep,
  { label: string; color: string; badgeColor: string }
> = {
  solicitado: {
    label: "1. Solicitado",
    color: "from-slate-600 to-slate-700",
    badgeColor: "bg-slate-800 text-slate-300",
  },
  validando: {
    label: "2. Validando (IA)",
    color: "from-blue-600 to-indigo-600",
    badgeColor: "bg-blue-500/20 text-blue-300",
  },
  exames_definidos: {
    label: "3. Exames Definidos",
    color: "from-purple-600 to-violet-600",
    badgeColor: "bg-purple-500/20 text-purple-300",
  },
  clinica_selecionada: {
    label: "4. Clínica Selecionada",
    color: "from-cyan-600 to-teal-600",
    badgeColor: "bg-cyan-500/20 text-cyan-300",
  },
  agendado: {
    label: "5. Agendado",
    color: "from-amber-600 to-orange-600",
    badgeColor: "bg-amber-500/20 text-amber-300",
  },
  kit_montado: {
    label: "6. Kit Montado",
    color: "from-indigo-600 to-blue-600",
    badgeColor: "bg-indigo-500/20 text-indigo-300",
  },
  kit_enviado: {
    label: "7. Kit Enviado",
    color: "from-cyan-600 to-emerald-600",
    badgeColor: "bg-cyan-500/20 text-cyan-300",
  },
  clinica_confirmou: {
    label: "8. Clínica Confirmou",
    color: "from-teal-600 to-emerald-600",
    badgeColor: "bg-teal-500/20 text-teal-300",
  },
  exame_realizado: {
    label: "9. Exame Realizado",
    color: "from-emerald-600 to-green-600",
    badgeColor: "bg-emerald-500/20 text-emerald-300",
  },
  aso_concluido: {
    label: "10. ASO Concluído",
    color: "from-green-600 to-emerald-500",
    badgeColor: "bg-green-500/20 text-green-300",
  },
};

export const INITIAL_ASO_REQUESTS: AsoRequest[] = [];
