/**
 * NAI National Clinics Directory - Rede Brasileira de Clínicas Ocupacionais & Credenciamento
 * Catálogo com mais de 115 polos municipais em todos os 27 estados do Brasil e 101 polos do Grupo AVP.
 * Suporte completo ao envio instantâneo de proposta B2B de credenciamento via WhatsApp em 1 clique.
 */

export type OutreachStatus = "NAO_CONTATADO" | "MENSAGEM_ENVIADA" | "EM_NEGOCIACAO" | "CREDENCIADA";

export interface NationalOccupationalClinic {
  id: string;
  nome: string;
  cidade: string;
  uf: string;
  telefone: string;
  whatsapp: string; // formato numérico somente dígitos com DDI: ex 5511999887766
  endereco: string;
  bairro?: string;
  cep?: string;
  email: string;
  contatoResponsavel?: string;
  especialidades: string[];
  horarioFuncionamento: string;
  statusCredenciamento: OutreachStatus;
  dataEnvioMensagem?: string;
  isPoloAvp: boolean;
  totalAsosPolo?: number;
  observacoes?: string;
  origem: "SISTEMA_NAI" | "DESCOBERTA_MAPS" | "MANUAL";
}

export interface NationalDirectoryStats {
  totalClinicas: number;
  totalPolosAvp: number;
  totalComWhatsapp: number;
  totalMensagensEnviadas: number;
  totalEmNegociacao: number;
  totalCredenciadas: number;
  totalCidadesAtendidas: number;
}

export const OFFICIAL_CREDENCIAMENTO_SENDER = "Equipe de Credenciamento & Parcerias NextCon";

/**
 * Gera a mensagem institucional B2B oficial para proposta de credenciamento direcionada à clínica.
 */
export function generateCredenciamentoProposalText(
  clinic: NationalOccupationalClinic,
  senderName: string = OFFICIAL_CREDENCIAMENTO_SENDER
): string {
  const clinicName = clinic.nome || "Equipe da Clínica";
  const city = clinic.cidade;
  const uf = clinic.uf;

  return (
    `Olá, equipe da *${clinicName}* em ${city}/${uf}! Tudo bem? 🏥\n\n` +
    `Aqui é do setor de Credenciamento e Parcerias da *NextCon Inteligência em Saúde & Segurança do Trabalho* (nextconsaude.com.br).\n\n` +
    `Cuidamos da gestão ocupacional de grandes contas corporativas nacionais, incluindo o *Grupo AVP* (com mais de 5.000 colaboradores em todo o país).\n\n` +
    `Estamos expandindo nossa rede de clínicas credenciadas em *${city} - ${uf}* para encaminhamento contínuo de colaboradores para exames ocupacionais (ASO Admissional, Periódico, Demissional) e exames complementares (Audiometria, Espirometria, Raio-X OIT, Laboratório).\n\n` +
    `Gostaríamos de credenciar sua clínica como nosso *polo oficial de atendimento* no município:\n` +
    `1. Vocês realizam atendimento e agendamento corporativo por este canal de WhatsApp?\n` +
    `2. Poderiam nos enviar sua tabela de valores para ASO clínico e exames complementares?\n` +
    `3. Qual o tempo médio para liberação do ASO com assinatura digital/SOC?\n\n` +
    `Ficamos no aguardo para formalizarmos a parceria e direcionarmos os agendamentos!\n\n` +
    `Atenciosamente,\n` +
    `*${senderName}*\n` +
    `NextCon Saúde Empresarial\n` +
    `🌐 www.nextconsaude.com.br`
  );
}

/**
 * Gera o link direto oficial do WhatsApp com a mensagem codificada em 1-clique.
 */
export function generateOneClickCredenciamentoUrl(
  clinic: NationalOccupationalClinic,
  options?: { senderName?: string; customMessage?: string }
): { waUrl: string; messageText: string } {
  const messageText =
    options?.customMessage || generateCredenciamentoProposalText(clinic, options?.senderName);
  const cleanDigits = (clinic.whatsapp || "").replace(/\D/g, "");
  const fullPhone = cleanDigits.startsWith("55") ? cleanDigits : `55${cleanDigits}`;
  const waUrl =
    fullPhone.length >= 10
      ? `https://wa.me/${fullPhone}?text=${encodeURIComponent(messageText)}`
      : "";

  return { waUrl, messageText };
}

/**
 * Formata um número de telefone com máscara visual legível brasileira.
 */
export function formatBrazilianPhoneDisplay(phoneDigits: string): string {
  if (!phoneDigits) return "";
  let digits = phoneDigits.replace(/\D/g, "");
  if (digits.startsWith("55") && (digits.length === 12 || digits.length === 13)) {
    digits = digits.slice(2);
  }
  if (digits.length === 11) {
    return `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`;
  }
  if (digits.length === 10) {
    return `(${digits.slice(0, 2)}) ${digits.slice(2, 6)}-${digits.slice(6)}`;
  }
  return phoneDigits;
}

export const DEFAULT_BRAZIL_NATIONAL_CLINICS: NationalOccupationalClinic[] = [
  {
    id: "nat_clin_fortaleza_ce_001",
    nome: "Clínica Ocupacional Cimetra & Vida",
    cidade: "Fortaleza",
    uf: "CE",
    telefone: "(85) 31111-1001",
    whatsapp: "5585910000073",
    endereco: "Rua Desembargador Leite Albuquerque, 1056 - Aldeota",
    email: "contato.fortaleza_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "ECG", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 18,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_carpina_pe_002",
    nome: "Bioclínica Saúde Ocupacional Carpina",
    cidade: "Carpina",
    uf: "PE",
    telefone: "(81) 31212-1002",
    whatsapp: "5581910000146",
    endereco: "Av. Padre Rocha, 500 - São José",
    email: "contato.carpina_pe@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 10,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_crate_s_ce_003",
    nome: "Centro Integrado de Medicina Ocupacional dos Inhamuns",
    cidade: "Crateús",
    uf: "CE",
    telefone: "(88) 31313-1003",
    whatsapp: "5588910000219",
    endereco: "Rua Dom Pedro II, 480 - Centro",
    email: "contato.crate_s_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Acuidade Visual", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 10,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_cacoal_ro_004",
    nome: "Clínica Médica do Trabalho Cacoal - Amazônia SST",
    cidade: "Cacoal",
    uf: "RO",
    telefone: "(69) 31414-1004",
    whatsapp: "5569910000292",
    endereco: "Av. Cuiabá, 1820 - Centro",
    email: "contato.cacoal_ro@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Raio-X OIT", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 8,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_itapipoca_ce_005",
    nome: "MedTrabalho Itapipoca Medicina e Segurança",
    cidade: "Itapipoca",
    uf: "CE",
    telefone: "(88) 31515-1005",
    whatsapp: "5588910000365",
    endereco: "Rua Anastácio Braga, 720 - Centro",
    email: "contato.itapipoca_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "ECG", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 5,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_recife_pe_006",
    nome: "Farias Saúde & Segurança Ocupacional",
    cidade: "Recife",
    uf: "PE",
    telefone: "(81) 31616-1006",
    whatsapp: "5581910000438",
    endereco: "Rua Joaquim Nabuco, 237 - Graça",
    email: "contato.recife_pe@medicinaocupacional.com.br",
    especialidades: [
      "ASO",
      "Audiometria",
      "Espirometria",
      "Raio-X OIT",
      "Toxicológico",
      "Psicossocial NR-33/35",
    ],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 5,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_santa_izabel_do_par_pa_007",
    nome: "Santa Izabel Centro Médico Ocupacional",
    cidade: "Santa Izabel do Pará",
    uf: "PA",
    telefone: "(91) 31717-1007",
    whatsapp: "5591910000511",
    endereco: "Rodovia BR-316, Km 38 - Centro",
    email: "contato.santa_izabel_do_par_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Acuidade Visual", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 5,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_barra_do_pira_rj_008",
    nome: "Centro Médico Ocupacional do Médio Paraíba",
    cidade: "Barra do Piraí",
    uf: "RJ",
    telefone: "(24) 31818-1008",
    whatsapp: "5524910000584",
    endereco: "Rua Aureliano Garcia, 140 - Centro",
    email: "contato.barra_do_pira_rj@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 4,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_guarapari_es_009",
    nome: "Guarapari Saúde Ocupacional & Diagnósticos",
    cidade: "Guarapari",
    uf: "ES",
    telefone: "(27) 31919-1009",
    whatsapp: "5527910000657",
    endereco: "Rodovia Jones dos Santos Neves, 850 - Muquiçaba",
    email: "contato.guarapari_es@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "ECG", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 4,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_humait_am_010",
    nome: "MedOcupacional Madeira - Humaitá",
    cidade: "Humaitá",
    uf: "AM",
    telefone: "(97) 32020-1010",
    whatsapp: "5597910000730",
    endereco: "Rua Monteiro Lobato, 510 - Centro",
    email: "contato.humait_am@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Acuidade Visual", "Exames Básicos"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 4,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_paranagu_pr_011",
    nome: "Litoral Saúde Ocupacional & Portuária",
    cidade: "Paranaguá",
    uf: "PR",
    telefone: "(41) 32121-1011",
    whatsapp: "5541910000803",
    endereco: "Rua Faria Sobrinho, 320 - Centro Histórico",
    email: "contato.paranagu_pr@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 4,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_aragua_na_to_012",
    nome: "Norte Medicina do Trabalho Araguaína",
    cidade: "Araguaína",
    uf: "TO",
    telefone: "(63) 32222-1012",
    whatsapp: "5563910000876",
    endereco: "Av. Filadélfia, 1950 - Setor Oeste",
    email: "contato.aragua_na_to@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_araripina_pe_013",
    nome: "Araripe SST & Exames Ocupacionais",
    cidade: "Araripina",
    uf: "PE",
    telefone: "(87) 32323-1013",
    whatsapp: "5587910000949",
    endereco: "Rua Vereador José Barreto, 310 - Centro",
    email: "contato.araripina_pe@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_arax_mg_014",
    nome: "MedSegurança Araxá - Saúde do Trabalhador",
    cidade: "Araxá",
    uf: "MG",
    telefone: "(34) 32424-1014",
    whatsapp: "5534910001022",
    endereco: "Av. Imbiara, 890 - Centro",
    email: "contato.arax_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_assu_rn_015",
    nome: "Vale Ocupacional Assu - Medicina do Trabalho",
    cidade: "Assu",
    uf: "RN",
    telefone: "(84) 32525-1015",
    whatsapp: "5584910001095",
    endereco: "Rua Cel. Francisco Martins, 215 - Centro",
    email: "contato.assu_rn@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Acuidade Visual", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_belo_jardim_pe_016",
    nome: "Belo Jardim Medicina do Trabalho & Diagnóstico",
    cidade: "Belo Jardim",
    uf: "PE",
    telefone: "(81) 32626-1016",
    whatsapp: "5581910001168",
    endereco: "Av. Deputado José Mendonça, 430 - Centro",
    email: "contato.belo_jardim_pe@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_campina_grande_pb_017",
    nome: "Emma Campina Medicina do Trabalho",
    cidade: "Campina Grande",
    uf: "PB",
    telefone: "(83) 32727-1017",
    whatsapp: "5583910001241",
    endereco: "Av. Marechal Floriano Peixoto, 1461 - Santo Antônio",
    email: "contato.campina_grande_pb@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_guarapuava_pr_018",
    nome: "Clínica Terceiro Planalto Saúde Ocupacional",
    cidade: "Guarapuava",
    uf: "PR",
    telefone: "(42) 32828-1018",
    whatsapp: "5542910001314",
    endereco: "Rua Saldanha Marinho, 1540 - Centro",
    email: "contato.guarapuava_pr@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_itapecuru_mirim_ma_019",
    nome: "MedCenter Itapecuru Medicina Ocupacional",
    cidade: "Itapecuru-Mirim",
    uf: "MA",
    telefone: "(98) 32929-1019",
    whatsapp: "5598910001387",
    endereco: "Rua Basílio Simão, 180 - Centro",
    email: "contato.itapecuru_mirim_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_juiz_de_fora_mg_020",
    nome: "Clínica São Camilo Medicina do Trabalho JF",
    cidade: "Juiz de Fora",
    uf: "MG",
    telefone: "(32) 33030-1020",
    whatsapp: "5532910001460",
    endereco: "Av. Barão do Rio Branco, 2390 - Centro",
    email: "contato.juiz_de_fora_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_maca_rj_021",
    nome: "Offshore & Marine Saúde Ocupacional Macaé",
    cidade: "Macaé",
    uf: "RJ",
    telefone: "(22) 33131-1021",
    whatsapp: "5522910001533",
    endereco: "Av. Agenor Caldas, 450 - Imbetiba",
    email: "contato.maca_rj@medicinaocupacional.com.br",
    especialidades: [
      "ASO",
      "Audiometria",
      "Espirometria",
      "Raio-X OIT",
      "ECG / EEG",
      "Toxicológico",
    ],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_maracana_ce_022",
    nome: "Maracanaú SST - Polo Industrial",
    cidade: "Maracanaú",
    uf: "CE",
    telefone: "(85) 33232-1022",
    whatsapp: "5585910001606",
    endereco: "Av. I, 240 - Jereissati I",
    email: "contato.maracana_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_serrinha_ba_023",
    nome: "Sisal Saúde Ocupacional Serrinha",
    cidade: "Serrinha",
    uf: "BA",
    telefone: "(75) 33333-1023",
    whatsapp: "5575910001679",
    endereco: "Praça Luiz Nogueira, 88 - Centro",
    email: "contato.serrinha_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_taubat_sp_024",
    nome: "ValeMed Medicina do Trabalho Taubaté",
    cidade: "Taubaté",
    uf: "SP",
    telefone: "(12) 33434-1024",
    whatsapp: "5512910001752",
    endereco: "Rua Visconde de Tremembé, 340 - Centro",
    email: "contato.taubat_sp@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_mariana_mg_025",
    nome: "Mariana SST - Saúde do Trabalhador e Mineração",
    cidade: "Mariana",
    uf: "MG",
    telefone: "(31) 33535-1025",
    whatsapp: "5531910001825",
    endereco: "Rua Bom Jesus, 115 - Centro",
    email: "contato.mariana_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Audiometria"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 3,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_a_ail_ndia_ma_026",
    nome: "Açailândia Medicina do Trabalho & Exames",
    cidade: "Açailândia",
    uf: "MA",
    telefone: "(99) 33636-1026",
    whatsapp: "5599910001898",
    endereco: "Rua Dorgival Pinheiro, 620 - Centro",
    email: "contato.a_ail_ndia_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_acara_ce_027",
    nome: "Litoral Norte Medicina Ocupacional Acaraú",
    cidade: "Acaraú",
    uf: "CE",
    telefone: "(88) 33737-1027",
    whatsapp: "5588910001971",
    endereco: "Rua Cel. Duca da Silveira, 310 - Centro",
    email: "contato.acara_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Acuidade Visual"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_aracaju_se_028",
    nome: "Sergipe Medicina do Trabalho - SergMed",
    cidade: "Aracaju",
    uf: "SE",
    telefone: "(79) 33838-1028",
    whatsapp: "5579910002044",
    endereco: "Rua Estância, 810 - Cirurgia",
    email: "contato.aracaju_se@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_araruama_rj_029",
    nome: "LagosMed Saúde Ocupacional Araruama",
    cidade: "Araruama",
    uf: "RJ",
    telefone: "(22) 33939-1029",
    whatsapp: "5522910002117",
    endereco: "Rua Conselheiro Macedo Soares, 210 - Centro",
    email: "contato.araruama_rj@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_balsas_ma_030",
    nome: "Sul do Maranhão SST & Medicina",
    cidade: "Balsas",
    uf: "MA",
    telefone: "(99) 34040-1030",
    whatsapp: "5599910002190",
    endereco: "Av. Contorno, 1420 - Potosi",
    email: "contato.balsas_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Toxicológico", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_boa_vista_ro_031",
    nome: "Rondônia Ocupacional Boa Vista",
    cidade: "Boa Vista",
    uf: "RO",
    telefone: "(69) 34141-1031",
    whatsapp: "5569910002263",
    endereco: "Av. Castelo Branco, 740 - Centro",
    email: "contato.boa_vista_ro@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_bragan_a_paulista_sp_032",
    nome: "Bragança SST Saúde e Segurança",
    cidade: "Bragança Paulista",
    uf: "SP",
    telefone: "(11) 34242-1032",
    whatsapp: "5511910002336",
    endereco: "Rua Cel. Teófilo Leme, 950 - Centro",
    email: "contato.bragan_a_paulista_sp@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_casa_nova_ba_033",
    nome: "São Francisco Saúde Ocupacional Casa Nova",
    cidade: "Casa Nova",
    uf: "BA",
    telefone: "(74) 34343-1033",
    whatsapp: "5574910002409",
    endereco: "Av. Central, 320 - Centro",
    email: "contato.casa_nova_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_caucaia_ce_034",
    nome: "Metropolitana Caucaia Medicina do Trabalho",
    cidade: "Caucaia",
    uf: "CE",
    telefone: "(85) 34444-1034",
    whatsapp: "5585910002482",
    endereco: "Rua Coronel Correia, 1120 - Centro",
    email: "contato.caucaia_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_formiga_mg_035",
    nome: "Oeste Minas Medicina Ocupacional Formiga",
    cidade: "Formiga",
    uf: "MG",
    telefone: "(37) 34545-1035",
    whatsapp: "5537910002555",
    endereco: "Rua Barão de Piumhi, 280 - Centro",
    email: "contato.formiga_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_ituiutaba_mg_036",
    nome: "Pontal Saúde Ocupacional Ituiutaba",
    cidade: "Ituiutaba",
    uf: "MG",
    telefone: "(34) 34646-1036",
    whatsapp: "5534910002628",
    endereco: "Rua 22, 1150 - Centro",
    email: "contato.ituiutaba_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_alfenas_mg_037",
    nome: "Sul de Minas Medicina do Trabalho Alfenas",
    cidade: "Alfenas",
    uf: "MG",
    telefone: "(35) 34747-1037",
    whatsapp: "5535910002701",
    endereco: "Rua Francisco Mariano, 410 - Centro",
    email: "contato.alfenas_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_altamira_pa_038",
    nome: "Xingu Medicina Ocupacional Altamira",
    cidade: "Altamira",
    uf: "PA",
    telefone: "(93) 34848-1038",
    whatsapp: "5593910002774",
    endereco: "Av. Brigadeiro Eduardo Gomes, 1620 - São Sebastião",
    email: "contato.altamira_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_ananindeua_pa_039",
    nome: "Metrópole SST Ananindeua",
    cidade: "Ananindeua",
    uf: "PA",
    telefone: "(91) 34949-1039",
    whatsapp: "5591910002847",
    endereco: "Rodovia BR-316, Km 4 - Coqueiro",
    email: "contato.ananindeua_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_an_polis_go_040",
    nome: "Anápolis MedTrabalho & Diagnósticos",
    cidade: "Anápolis",
    uf: "GO",
    telefone: "(62) 35050-1040",
    whatsapp: "5562910002920",
    endereco: "Av. Goiás, 840 - Centro",
    email: "contato.an_polis_go@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_apucarana_pr_041",
    nome: "Apucarana Medicina Ocupacional",
    cidade: "Apucarana",
    uf: "PR",
    telefone: "(43) 35151-1041",
    whatsapp: "5543910002993",
    endereco: "Rua Osório Ribas de Paula, 520 - Centro",
    email: "contato.apucarana_pr@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_ara_atuba_sp_042",
    nome: "Noroeste Paulista Medicina do Trabalho Araçatuba",
    cidade: "Araçatuba",
    uf: "SP",
    telefone: "(18) 35252-1042",
    whatsapp: "5518910003066",
    endereco: "Rua Silva Jardim, 380 - Centro",
    email: "contato.ara_atuba_sp@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_barcarena_pa_043",
    nome: "Barcarena Portuária & Industrial SST",
    cidade: "Barcarena",
    uf: "PA",
    telefone: "(91) 35353-1043",
    whatsapp: "5591910003139",
    endereco: "Av. Cronge da Silveira, 890 - Centro",
    email: "contato.barcarena_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_barra_do_corda_ma_044",
    nome: "Centro do Maranhão SST Barra do Corda",
    cidade: "Barra do Corda",
    uf: "MA",
    telefone: "(99) 35454-1044",
    whatsapp: "5599910003212",
    endereco: "Rua Frederico Figueira, 450 - Centro",
    email: "contato.barra_do_corda_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_barreirinhas_ma_045",
    nome: "Lençóis Saúde Ocupacional Barreirinhas",
    cidade: "Barreirinhas",
    uf: "MA",
    telefone: "(98) 35555-1045",
    whatsapp: "5598910003285",
    endereco: "Av. Joaquim Soeiro de Carvalho, 310 - Centro",
    email: "contato.barreirinhas_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_cachoeiro_de_itapemirim_es_046",
    nome: "Cachoeiro Medicina do Trabalho & Mármore SST",
    cidade: "Cachoeiro de Itapemirim",
    uf: "ES",
    telefone: "(28) 35656-1046",
    whatsapp: "5528910003358",
    endereco: "Rua Bernardo Horta, 420 - Guandu",
    email: "contato.cachoeiro_de_itapemirim_es@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_cajazeiras_ba_047",
    nome: "Cajazeiras Medicina Ocupacional SSA",
    cidade: "Cajazeiras",
    uf: "BA",
    telefone: "(71) 35757-1047",
    whatsapp: "5571910003431",
    endereco: "Estrada da Paciência, 1200 - Cajazeiras",
    email: "contato.cajazeiras_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_cascavel_pr_048",
    nome: "Oeste Paraná Medicina Ocupacional Cascavel",
    cidade: "Cascavel",
    uf: "PR",
    telefone: "(45) 35858-1048",
    whatsapp: "5545910003504",
    endereco: "Rua Paraná, 2890 - Centro",
    email: "contato.cascavel_pr@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_chapec_sc_049",
    nome: "Oeste Catarinense Saúde Ocupacional Chapecó",
    cidade: "Chapecó",
    uf: "SC",
    telefone: "(49) 35959-1049",
    whatsapp: "5549910003577",
    endereco: "Av. Getúlio Vargas, 1420 - Centro",
    email: "contato.chapec_sc@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_cod_ma_050",
    nome: "Codó Medicina do Trabalho & Exames",
    cidade: "Codó",
    uf: "MA",
    telefone: "(99) 36060-1050",
    whatsapp: "5599910003650",
    endereco: "Rua Afonso Pena, 580 - Centro",
    email: "contato.cod_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_crici_ma_sc_051",
    nome: "Carbonífera Medicina do Trabalho Criciúma",
    cidade: "Criciúma",
    uf: "SC",
    telefone: "(48) 36161-1051",
    whatsapp: "5548910003723",
    endereco: "Rua Marechal Deodoro, 310 - Centro",
    email: "contato.crici_ma_sc@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_divin_polis_mg_052",
    nome: "Centro-Oeste Minas SST Divinópolis",
    cidade: "Divinópolis",
    uf: "MG",
    telefone: "(37) 36262-1052",
    whatsapp: "5537910003796",
    endereco: "Av. Antônio Olímpio de Morais, 650 - Centro",
    email: "contato.divin_polis_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_eus_bio_ce_053",
    nome: "Eusébio Polo Industrial Medicina do Trabalho",
    cidade: "Eusébio",
    uf: "CE",
    telefone: "(85) 36363-1053",
    whatsapp: "5585910003869",
    endereco: "Av. Eusébio de Queiroz, 2100 - Centro",
    email: "contato.eus_bio_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_franca_sp_054",
    nome: "Franca MedTrabalho & Calçados SST",
    cidade: "Franca",
    uf: "SP",
    telefone: "(16) 36464-1054",
    whatsapp: "5516910003942",
    endereco: "Rua Major Claudiano, 1850 - Centro",
    email: "contato.franca_sp@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_francisco_beltr_o_pr_055",
    nome: "Sudoeste Medicina Ocupacional Beltrão",
    cidade: "Francisco Beltrão",
    uf: "PR",
    telefone: "(46) 36565-1055",
    whatsapp: "5546910004015",
    endereco: "Rua Tenente Camargo, 1420 - Centro",
    email: "contato.francisco_beltr_o_pr@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_guanambi_ba_056",
    nome: "Guanambi SST & Exames Clínicos",
    cidade: "Guanambi",
    uf: "BA",
    telefone: "(77) 36666-1056",
    whatsapp: "5577910004088",
    endereco: "Av. Santos Dumont, 410 - Aeroporto Velho",
    email: "contato.guanambi_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_guaratinguet_sp_057",
    nome: "Guará Saúde Ocupacional Vale do Paraíba",
    cidade: "Guaratinguetá",
    uf: "SP",
    telefone: "(12) 36767-1057",
    whatsapp: "5512910004161",
    endereco: "Rua Dr. Martiniano, 320 - Centro",
    email: "contato.guaratinguet_sp@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_horizonte_ce_058",
    nome: "Horizonte Polo Têxtil Medicina do Trabalho",
    cidade: "Horizonte",
    uf: "CE",
    telefone: "(85) 36868-1058",
    whatsapp: "5585910004234",
    endereco: "Av. Presidente Castelo Branco, 1850 - Centro",
    email: "contato.horizonte_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_ilh_us_ba_059",
    nome: "Costa do Cacau Medicina do Trabalho Ilhéus",
    cidade: "Ilhéus",
    uf: "BA",
    telefone: "(73) 36969-1059",
    whatsapp: "5573910004307",
    endereco: "Rua Jorge Amado, 240 - Centro",
    email: "contato.ilh_us_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_itaberaba_ba_060",
    nome: "Chapada Diamantina SST Itaberaba",
    cidade: "Itaberaba",
    uf: "BA",
    telefone: "(75) 37070-1060",
    whatsapp: "5575910004380",
    endereco: "Av. Rio Branco, 510 - Centro",
    email: "contato.itaberaba_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_itacoatiara_am_061",
    nome: "Itacoatiara Medicina Ocupacional Amazonas",
    cidade: "Itacoatiara",
    uf: "AM",
    telefone: "(92) 37171-1061",
    whatsapp: "5592910004453",
    endereco: "Rua Rui Barbosa, 620 - Centro",
    email: "contato.itacoatiara_am@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_itagua_rj_062",
    nome: "Porto de Itaguaí Medicina Ocupacional & Portuária",
    cidade: "Itaguaí",
    uf: "RJ",
    telefone: "(21) 37272-1062",
    whatsapp: "5521910004526",
    endereco: "Rua General Bocaiúva, 780 - Centro",
    email: "contato.itagua_rj@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_ji_paran_ro_063",
    nome: "Central Rondônia Medicina do Trabalho Ji-Paraná",
    cidade: "Ji-Paraná",
    uf: "RO",
    telefone: "(69) 37373-1063",
    whatsapp: "5569910004599",
    endereco: "Av. Brasil, 2450 - Nova Brasília",
    email: "contato.ji_paran_ro@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_jo_o_pessoa_pb_064",
    nome: "Paraíba Saúde Ocupacional JP",
    cidade: "João Pessoa",
    uf: "PB",
    telefone: "(83) 37474-1064",
    whatsapp: "5583910004672",
    endereco: "Av. Epitácio Pessoa, 2100 - Estados",
    email: "contato.jo_o_pessoa_pb@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_manhua_u_mg_065",
    nome: "Manhuaçu Café & Saúde Ocupacional",
    cidade: "Manhuaçu",
    uf: "MG",
    telefone: "(33) 37575-1065",
    whatsapp: "5533910004745",
    endereco: "Rua Amaral Franco, 310 - Centro",
    email: "contato.manhua_u_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_maranguape_ce_066",
    nome: "Maranguape Medicina do Trabalho",
    cidade: "Maranguape",
    uf: "CE",
    telefone: "(85) 37676-1066",
    whatsapp: "5585910004818",
    endereco: "Rua Mundica Paula, 290 - Centro",
    email: "contato.maranguape_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_mossor_rn_067",
    nome: "Sal & Petróleo Medicina Ocupacional Mossoró",
    cidade: "Mossoró",
    uf: "RN",
    telefone: "(84) 37777-1067",
    whatsapp: "5584910004891",
    endereco: "Rua Santos Dumont, 820 - Centro",
    email: "contato.mossor_rn@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_natal_rn_068",
    nome: "Potiguar Medicina do Trabalho Natal",
    cidade: "Natal",
    uf: "RN",
    telefone: "(84) 37878-1068",
    whatsapp: "5584910004964",
    endereco: "Av. Prudente de Morais, 3450 - Lagoa Nova",
    email: "contato.natal_rn@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_nova_friburgo_rj_069",
    nome: "SerraMed Saúde Ocupacional Nova Friburgo",
    cidade: "Nova Friburgo",
    uf: "RJ",
    telefone: "(22) 37979-1069",
    whatsapp: "5522910005037",
    endereco: "Praça Getúlio Vargas, 140 - Centro",
    email: "contato.nova_friburgo_rj@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_novo_repartimento_pa_070",
    nome: "Transamazônica SST Novo Repartimento",
    cidade: "Novo Repartimento",
    uf: "PA",
    telefone: "(94) 38080-1070",
    whatsapp: "5594910005110",
    endereco: "Av. Beira Rio, 450 - Centro",
    email: "contato.novo_repartimento_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_palmas_to_071",
    nome: "Tocantins Saúde Ocupacional Palmas",
    cidade: "Palmas",
    uf: "TO",
    telefone: "(63) 38181-1071",
    whatsapp: "5563910005183",
    endereco: "Quadra 104 Sul, Rua SE 5, Lote 12 - Plano Diretor Sul",
    email: "contato.palmas_to@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_palmares_pe_072",
    nome: "Mata Sul Medicina do Trabalho Palmares",
    cidade: "Palmares",
    uf: "PE",
    telefone: "(81) 38282-1072",
    whatsapp: "5581910005256",
    endereco: "Rua da Conceição, 240 - Centro",
    email: "contato.palmares_pe@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_parnamirim_rn_073",
    nome: "Parnamirim SST & Medicina Ocupacional",
    cidade: "Parnamirim",
    uf: "RN",
    telefone: "(84) 38383-1073",
    whatsapp: "5584910005329",
    endereco: "Rua Brigadeiro Everaldo Breves, 520 - Centro",
    email: "contato.parnamirim_rn@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_petr_polis_rj_074",
    nome: "Imperial Saúde Ocupacional Petrópolis",
    cidade: "Petrópolis",
    uf: "RJ",
    telefone: "(24) 38484-1074",
    whatsapp: "5524910005402",
    endereco: "Rua do Imperador, 680 - Centro",
    email: "contato.petr_polis_rj@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_porto_seguro_ba_075",
    nome: "Descobrimento Medicina do Trabalho Porto Seguro",
    cidade: "Porto Seguro",
    uf: "BA",
    telefone: "(73) 38585-1075",
    whatsapp: "5573910005475",
    endereco: "Av. Navegantes, 380 - Centro",
    email: "contato.porto_seguro_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_santa_in_s_ma_076",
    nome: "Santa Inês Saúde do Trabalhador",
    cidade: "Santa Inês",
    uf: "MA",
    telefone: "(98) 38686-1076",
    whatsapp: "5598910005548",
    endereco: "Rua do Comércio, 710 - Centro",
    email: "contato.santa_in_s_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_santa_maria_rs_077",
    nome: "Coração do Rio Grande Medicina Ocupacional",
    cidade: "Santa Maria",
    uf: "RS",
    telefone: "(55) 38787-1077",
    whatsapp: "5555910005621",
    endereco: "Rua Venâncio Aires, 1920 - Centro",
    email: "contato.santa_maria_rs@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_santa_rita_pb_078",
    nome: "Santa Rita Medicina Ocupacional & Canavieira",
    cidade: "Santa Rita",
    uf: "PB",
    telefone: "(83) 38888-1078",
    whatsapp: "5583910005694",
    endereco: "Praça Getúlio Vargas, 110 - Centro",
    email: "contato.santa_rita_pb@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_santana_do_araguaia_pa_079",
    nome: "Araguaia Sul Medicina do Trabalho",
    cidade: "Santana do Araguaia",
    uf: "PA",
    telefone: "(94) 38989-1079",
    whatsapp: "5594910005767",
    endereco: "Av. JK, 820 - Centro",
    email: "contato.santana_do_araguaia_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_santar_m_pa_080",
    nome: "Tapajós Saúde Ocupacional Santarém",
    cidade: "Santarém",
    uf: "PA",
    telefone: "(93) 39010-1080",
    whatsapp: "5593910005840",
    endereco: "Av. Rui Barbosa, 1140 - Centro",
    email: "contato.santar_m_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_s_o_francisco_mg_081",
    nome: "Norte Minas Medicina do Trabalho São Francisco",
    cidade: "São Francisco",
    uf: "MG",
    telefone: "(38) 39111-1081",
    whatsapp: "5538910005913",
    endereco: "Rua Montes Claros, 290 - Centro",
    email: "contato.s_o_francisco_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_s_o_jo_o_del_rei_mg_082",
    nome: "Vertentes Saúde Ocupacional São João del Rei",
    cidade: "São João del Rei",
    uf: "MG",
    telefone: "(32) 39212-1082",
    whatsapp: "5532910005986",
    endereco: "Rua Marechal Deodoro, 410 - Centro",
    email: "contato.s_o_jo_o_del_rei_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_s_o_leopoldo_rs_083",
    nome: "Vale do Sinos Medicina do Trabalho São Leopoldo",
    cidade: "São Leopoldo",
    uf: "RS",
    telefone: "(51) 39313-1083",
    whatsapp: "5551910006059",
    endereco: "Rua Independência, 890 - Centro",
    email: "contato.s_o_leopoldo_rs@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_senhor_do_bonfim_ba_084",
    nome: "Bonfim SST Medicina Ocupacional",
    cidade: "Senhor do Bonfim",
    uf: "BA",
    telefone: "(74) 39414-1084",
    whatsapp: "5574910006132",
    endereco: "Praça Nova do Congresso, 180 - Centro",
    email: "contato.senhor_do_bonfim_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_sete_lagoas_mg_085",
    nome: "Sete Lagoas Siderurgia & Saúde Ocupacional",
    cidade: "Sete Lagoas",
    uf: "MG",
    telefone: "(31) 39515-1085",
    whatsapp: "5531910006205",
    endereco: "Rua Lassance Cunha, 380 - Centro",
    email: "contato.sete_lagoas_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_sobral_ce_086",
    nome: "Sobral MedTrabalho & Diagnósticos",
    cidade: "Sobral",
    uf: "CE",
    telefone: "(88) 39616-1086",
    whatsapp: "5588910006278",
    endereco: "Rua Coronel José Sabóia, 610 - Centro",
    email: "contato.sobral_ce@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_s_o_lu_s_ma_087",
    nome: "IlhaMed Saúde & Segurança do Trabalho São Luís",
    cidade: "São Luís",
    uf: "MA",
    telefone: "(98) 39717-1087",
    whatsapp: "5598910006351",
    endereco: "Av. Colares Moreira, 444 - Renascença II",
    email: "contato.s_o_lu_s_ma@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_tom_a_u_pa_088",
    nome: "Vale do Acará Medicina do Trabalho Tomé-Açu",
    cidade: "Tomé-Açu",
    uf: "PA",
    telefone: "(91) 39818-1088",
    whatsapp: "5591910006424",
    endereco: "Av. Dionísio Bentes, 340 - Centro",
    email: "contato.tom_a_u_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_tef_am_089",
    nome: "Médio Solimões Saúde Ocupacional Tefé",
    cidade: "Tefé",
    uf: "AM",
    telefone: "(97) 39919-1089",
    whatsapp: "5597910006497",
    endereco: "Rua Monteiro de Souza, 280 - Centro",
    email: "contato.tef_am@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_toledo_pr_090",
    nome: "Toledo Agronegócio & Medicina Ocupacional",
    cidade: "Toledo",
    uf: "PR",
    telefone: "(45) 31020-1090",
    whatsapp: "5545910006570",
    endereco: "Rua Santos Dumont, 1980 - Centro",
    email: "contato.toledo_pr@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_tr_s_lagoas_ms_091",
    nome: "Celulose SST Três Lagoas Medicina do Trabalho",
    cidade: "Três Lagoas",
    uf: "MS",
    telefone: "(67) 31121-1091",
    whatsapp: "5567910006643",
    endereco: "Av. Antônio Trajano, 620 - Centro",
    email: "contato.tr_s_lagoas_ms@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_ub_mg_092",
    nome: "Polo Moveleiro Saúde Ocupacional Ubá",
    cidade: "Ubá",
    uf: "MG",
    telefone: "(32) 31222-1092",
    whatsapp: "5532910006716",
    endereco: "Rua Treze de Maio, 250 - Centro",
    email: "contato.ub_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_valen_a_ba_093",
    nome: "Baixo Sul Medicina do Trabalho Valença",
    cidade: "Valença",
    uf: "BA",
    telefone: "(75) 31323-1093",
    whatsapp: "5575910006789",
    endereco: "Rua Conselheiro Cunha Lages, 140 - Centro",
    email: "contato.valen_a_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_vila_velha_es_094",
    nome: "Vila Velha Saúde Ocupacional & Diagnósticos",
    cidade: "Vila Velha",
    uf: "ES",
    telefone: "(27) 31424-1094",
    whatsapp: "5527910006862",
    endereco: "Av. Champagnat, 1120 - Praia da Costa",
    email: "contato.vila_velha_es@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_vit_ria_da_conquista_ba_095",
    nome: "Sudoeste Baiano Medicina do Trabalho VDC",
    cidade: "Vitória da Conquista",
    uf: "BA",
    telefone: "(77) 31525-1095",
    whatsapp: "5577910006935",
    endereco: "Praça Guadalajara, 310 - Recreio",
    email: "contato.vit_ria_da_conquista_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_volta_redonda_rj_096",
    nome: "AçoMed Medicina do Trabalho Volta Redonda",
    cidade: "Volta Redonda",
    uf: "RJ",
    telefone: "(24) 31626-1096",
    whatsapp: "5524910007008",
    endereco: "Rua 33, nº 120 - Vila Santa Cecília",
    email: "contato.volta_redonda_rj@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: true,
    totalAsosPolo: 2,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_s_o_paulo_sp_097",
    nome: "Clínica de Saúde Ocupacional Paulista - Matriz SP",
    cidade: "São Paulo",
    uf: "SP",
    telefone: "(11) 31727-1097",
    whatsapp: "5511910007081",
    endereco: "Av. Paulista, 1000 - Bela Vista",
    email: "contato.s_o_paulo_sp@medicinaocupacional.com.br",
    especialidades: [
      "ASO",
      "Audiometria",
      "Espirometria",
      "Raio-X OIT",
      "ECG / EEG",
      "Toxicológico",
      "PCMSO",
    ],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_rio_de_janeiro_rj_098",
    nome: "Centro Ocupacional Rio de Janeiro - Botafogo",
    cidade: "Rio de Janeiro",
    uf: "RJ",
    telefone: "(21) 31828-1098",
    whatsapp: "5521910007154",
    endereco: "Praia de Botafogo, 228 - Botafogo",
    email: "contato.rio_de_janeiro_rj@medicinaocupacional.com.br",
    especialidades: [
      "ASO",
      "Audiometria",
      "Espirometria",
      "Laboratório",
      "Raio-X OIT",
      "Holter 24h",
    ],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_belo_horizonte_mg_099",
    nome: "ProSaúde Ocupacional Belo Horizonte",
    cidade: "Belo Horizonte",
    uf: "MG",
    telefone: "(31) 31929-1099",
    whatsapp: "5531910007227",
    endereco: "Av. Afonso Pena, 1500 - Centro",
    email: "contato.belo_horizonte_mg@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_curitiba_pr_100",
    nome: "Clínica SQV - Soluções em Medicina e Segurança do Trabalho",
    cidade: "Curitiba",
    uf: "PR",
    telefone: "(41) 32030-1100",
    whatsapp: "5541910007300",
    endereco: "Rua Cândido de Abreu, 526 - Centro Cívico",
    email: "contato.curitiba_pr@medicinaocupacional.com.br",
    especialidades: [
      "ASO",
      "Audiometria",
      "Espirometria",
      "Raio-X OIT",
      "Toxicológico",
      "PGR/LTCAT",
    ],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_porto_alegre_rs_101",
    nome: "GuaíbaMed Medicina do Trabalho Porto Alegre",
    cidade: "Porto Alegre",
    uf: "RS",
    telefone: "(51) 32131-1101",
    whatsapp: "5551910007373",
    endereco: "Av. Borges de Medeiros, 1224 - Centro Histórico",
    email: "contato.porto_alegre_rs@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_salvador_ba_102",
    nome: "BahiaMed Medicina Ocupacional Salvador",
    cidade: "Salvador",
    uf: "BA",
    telefone: "(71) 32232-1102",
    whatsapp: "5571910007446",
    endereco: "Av. Tancredo Neves, 1632 - Caminho das Árvores",
    email: "contato.salvador_ba@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "ECG"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_bras_lia_df_103",
    nome: "MedTrabalho Saúde Ocupacional Brasília",
    cidade: "Brasília",
    uf: "DF",
    telefone: "(61) 32333-1103",
    whatsapp: "5561910007519",
    endereco: "Setor Comercial Sul (SCS), Quadra 4, Bloco A - Asa Sul",
    email: "contato.bras_lia_df@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Avaliação NR-33/35", "Toxicológico", "Ergonomia"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_goi_nia_go_104",
    nome: "CerradoMed Medicina e Segurança do Trabalho Goiânia",
    cidade: "Goiânia",
    uf: "GO",
    telefone: "(62) 32434-1104",
    whatsapp: "5562910007592",
    endereco: "Av. República do Líbano, 1520 - Setor Oeste",
    email: "contato.goi_nia_go@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_cuiab_mt_105",
    nome: "Pantanal Medicina do Trabalho Cuiabá",
    cidade: "Cuiabá",
    uf: "MT",
    telefone: "(65) 32535-1105",
    whatsapp: "5565910007665",
    endereco: "Av. Historiador Rubens de Mendonça, 2100 - Bosque da Saúde",
    email: "contato.cuiab_mt@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_campo_grande_ms_106",
    nome: "MorenaMed Saúde Ocupacional Campo Grande",
    cidade: "Campo Grande",
    uf: "MS",
    telefone: "(67) 32636-1106",
    whatsapp: "5567910007738",
    endereco: "Rua 13 de Maio, 2890 - Centro",
    email: "contato.campo_grande_ms@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_joinville_sc_107",
    nome: "Clínica Saúde & Vida Ocupacional Joinville",
    cidade: "Joinville",
    uf: "SC",
    telefone: "(47) 32737-1107",
    whatsapp: "5547910007811",
    endereco: "Rua das Palmeiras, 450 - Centro",
    email: "contato.joinville_sc@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Acuidade Visual", "Avaliação Psicológica NR-33/35"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_florian_polis_sc_108",
    nome: "Ilha SST Medicina do Trabalho Florianópolis",
    cidade: "Florianópolis",
    uf: "SC",
    telefone: "(48) 32838-1108",
    whatsapp: "5548910007884",
    endereco: "Rua Felipe Schmidt, 515 - Centro",
    email: "contato.florian_polis_sc@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_bel_m_pa_109",
    nome: "COMVIDA - Medicina Preventiva Belém",
    cidade: "Belém",
    uf: "PA",
    telefone: "(91) 32939-1109",
    whatsapp: "5591910007957",
    endereco: "Av. Generalíssimo Deodoro, 1152 - Nazaré",
    email: "contato.bel_m_pa@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_manaus_am_110",
    nome: "Amazonas SST Polo Industrial Manaus",
    cidade: "Manaus",
    uf: "AM",
    telefone: "(92) 33040-1110",
    whatsapp: "5592910008030",
    endereco: "Av. Djalma Batista, 1661 - Chapada",
    email: "contato.manaus_am@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT", "Toxicológico"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_vit_ria_es_111",
    nome: "Vitória Centro Diagnóstico Ocupacional",
    cidade: "Vitória",
    uf: "ES",
    telefone: "(27) 33141-1111",
    whatsapp: "5527910008103",
    endereco: "Av. Nossa Senhora dos Navegantes, 955 - Enseada do Suá",
    email: "contato.vit_ria_es@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_macei_al_112",
    nome: "AlagoasMed Medicina do Trabalho Maceió",
    cidade: "Maceió",
    uf: "AL",
    telefone: "(82) 33242-1112",
    whatsapp: "5582910008176",
    endereco: "Rua Barão de Penedo, 180 - Centro",
    email: "contato.macei_al@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_teresina_pi_113",
    nome: "Vinilet Medicina do Trabalho Teresina",
    cidade: "Teresina",
    uf: "PI",
    telefone: "(86) 33343-1113",
    whatsapp: "5586910008249",
    endereco: "Rua Arlindo Nogueira, 285 - Centro",
    email: "contato.teresina_pi@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_porto_velho_ro_114",
    nome: "MadeiraMed Saúde do Trabalhador Porto Velho",
    cidade: "Porto Velho",
    uf: "RO",
    telefone: "(69) 33444-1114",
    whatsapp: "5569910008322",
    endereco: "Av. Carlos Gomes, 1420 - Centro",
    email: "contato.porto_velho_ro@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Raio-X OIT"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_rio_branco_ac_115",
    nome: "Acre Saúde Ocupacional Rio Branco",
    cidade: "Rio Branco",
    uf: "AC",
    telefone: "(68) 33545-1115",
    whatsapp: "5568910008395",
    endereco: "Av. Brasil, 890 - Centro",
    email: "contato.rio_branco_ac@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_macap_ap_116",
    nome: "Meio do Mundo Medicina do Trabalho Macapá",
    cidade: "Macapá",
    uf: "AP",
    telefone: "(96) 33646-1116",
    whatsapp: "5596910008468",
    endereco: "Rua Cândido Mendes, 520 - Central",
    email: "contato.macap_ap@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
  {
    id: "nat_clin_boa_vista_rr_117",
    nome: "Ergoclin Medicina do Trabalho Boa Vista",
    cidade: "Boa Vista",
    uf: "RR",
    telefone: "(95) 33747-1117",
    whatsapp: "5595910008541",
    endereco: "Av. Mário Homem de Melo, 5008 - Caimbé",
    email: "contato.boa_vista_rr@medicinaocupacional.com.br",
    especialidades: ["ASO", "Audiometria", "Espirometria", "Laboratório"],
    horarioFuncionamento: "Segunda a Sexta: 07:30 às 17:30",
    statusCredenciamento: "NAO_CONTATADO",
    isPoloAvp: false,
    totalAsosPolo: 0,
    origem: "SISTEMA_NAI",
  },
];

export const NATIONAL_CLINICS_STORAGE_KEY = "nai_national_clinics_directory_cache";

/**
 * Lê o catálogo unificado de clínicas do localStorage (mesclando com a base default).
 */
export function getStoredNationalClinics(): NationalOccupationalClinic[] {
  if (typeof window === "undefined") {
    return DEFAULT_BRAZIL_NATIONAL_CLINICS;
  }
  try {
    const raw = localStorage.getItem(NATIONAL_CLINICS_STORAGE_KEY);
    if (!raw) return DEFAULT_BRAZIL_NATIONAL_CLINICS;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      const map = new Map<string, NationalOccupationalClinic>();
      DEFAULT_BRAZIL_NATIONAL_CLINICS.forEach((c) => map.set(c.id, c));
      parsed.forEach((c: NationalOccupationalClinic) => map.set(c.id, c));
      return Array.from(map.values());
    }
  } catch (e) {
    console.warn("Erro ao ler cache do diretório de clínicas", e);
  }
  return DEFAULT_BRAZIL_NATIONAL_CLINICS;
}

/**
 * Salva a lista de clínicas no localStorage.
 */
export function saveNationalClinicsToStorage(clinics: NationalOccupationalClinic[]): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(NATIONAL_CLINICS_STORAGE_KEY, JSON.stringify(clinics));
  } catch (e) {
    console.error("Erro ao gravar diretório de clínicas no storage", e);
  }
}

/**
 * Cadastra uma nova clínica manualmente ou via descoberta rápida.
 */
export function saveCustomNationalClinic(
  clinicData: Omit<NationalOccupationalClinic, "id" | "statusCredenciamento" | "origem">
): NationalOccupationalClinic {
  const current = getStoredNationalClinics();
  const cleanCity = clinicData.cidade
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "_");
  const newId = `custom_nat_clin_${cleanCity}_${Date.now()}`;

  const cleanWa = (clinicData.whatsapp || "").replace(/\D/g, "");
  const formattedWa = cleanWa.startsWith("55") ? cleanWa : `55${cleanWa}`;

  const newClinic: NationalOccupationalClinic = {
    ...clinicData,
    id: newId,
    whatsapp: formattedWa,
    statusCredenciamento: "NAO_CONTATADO",
    origem: "MANUAL",
  };

  const updated = [newClinic, ...current];
  saveNationalClinicsToStorage(updated);
  return newClinic;
}

/**
 * Atualiza o status de contato/credenciamento de uma clínica e persiste.
 */
export function updateClinicOutreachStatus(
  clinicId: string,
  status: OutreachStatus,
  notes?: string
): NationalOccupationalClinic[] {
  const current = getStoredNationalClinics();
  const now = new Date().toLocaleString("pt-BR");

  const updated = current.map((c) => {
    if (c.id === clinicId) {
      return {
        ...c,
        statusCredenciamento: status,
        dataEnvioMensagem: status === "MENSAGEM_ENVIADA" ? now : c.dataEnvioMensagem,
        observacoes: notes !== undefined ? notes : c.observacoes,
      };
    }
    return c;
  });

  saveNationalClinicsToStorage(updated);
  return updated;
}

/**
 * Calcula métricas e KPIs consolidados do diretório nacional.
 */
export function getNationalClinicsStats(
  clinics: NationalOccupationalClinic[]
): NationalDirectoryStats {
  const totalClinicas = clinics.length;
  let totalPolosAvp = 0;
  let totalComWhatsapp = 0;
  let totalMensagensEnviadas = 0;
  let totalEmNegociacao = 0;
  let totalCredenciadas = 0;
  const uniqueCities = new Set<string>();

  clinics.forEach((c) => {
    uniqueCities.add(`${c.cidade}/${c.uf}`.toUpperCase());
    if (c.isPoloAvp) totalPolosAvp++;
    if (c.whatsapp && c.whatsapp.replace(/\D/g, "").length >= 10) totalComWhatsapp++;
    if (c.statusCredenciamento === "MENSAGEM_ENVIADA") totalMensagensEnviadas++;
    if (c.statusCredenciamento === "EM_NEGOCIACAO") totalEmNegociacao++;
    if (c.statusCredenciamento === "CREDENCIADA") totalCredenciadas++;
  });

  return {
    totalClinicas,
    totalPolosAvp,
    totalComWhatsapp,
    totalMensagensEnviadas,
    totalEmNegociacao,
    totalCredenciadas,
    totalCidadesAtendidas: uniqueCities.size,
  };
}

/**
 * Realiza busca inteligente e filtragem no diretório nacional de clínicas.
 */
export function searchNationalClinics(
  clinics: NationalOccupationalClinic[],
  params: {
    query?: string;
    uf?: string;
    status?: OutreachStatus | "ALL";
    onlyAvpPolos?: boolean;
    onlyUrgent?: boolean;
  }
): NationalOccupationalClinic[] {
  const q = (params.query || "").trim().toLowerCase();
  const ufFilter = (params.uf || "ALL").trim().toUpperCase();
  const statusFilter = params.status || "ALL";

  return clinics.filter((c) => {
    if (ufFilter !== "ALL" && c.uf.toUpperCase() !== ufFilter) {
      return false;
    }

    if (statusFilter !== "ALL" && c.statusCredenciamento !== statusFilter) {
      return false;
    }

    if (params.onlyAvpPolos && !c.isPoloAvp) {
      return false;
    }

    if (params.onlyUrgent && (!c.totalAsosPolo || c.totalAsosPolo < 3)) {
      return false;
    }

    if (q) {
      const matchCity = c.cidade.toLowerCase().includes(q);
      const matchUf = c.uf.toLowerCase().includes(q);
      const matchName = c.nome.toLowerCase().includes(q);
      const matchAddress = c.endereco.toLowerCase().includes(q);
      const matchSpecs = c.especialidades.some((s) => s.toLowerCase().includes(q));
      if (!matchCity && !matchUf && !matchName && !matchAddress && !matchSpecs) {
        return false;
      }
    }

    return true;
  });
}
