export const DEMO_PROVIDERS = [
  {
    legacyId: "107",
    displayName: "PAULO SERGIO SOUSA CURVELO",
    email: "paulosergio.curvelo@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "7178", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "110",
    displayName: "Adelmo Marangoni Antoniazzi",
    email: "adelmo.antoniazzi@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "231549/D", type: "CREA" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: false, canManage: false },
  },
  {
    legacyId: "47",
    displayName: "ADEMAR DURANTE",
    email: "ademardurante@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "12444", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "87",
    displayName: "ADOLFO COCA MANCILLA",
    email: "adolfococamancilla@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "27766", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "8",
    displayName: "ADRIANE BARBOSA BOTELHO KUPPER",
    email: "adrianebarbosabotelh@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "29035", type: "CRM" },
    status: "INACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: false, canManage: false },
  },
  {
    legacyId: "6",
    displayName: "Adriane de Almeida G. da Conceição",
    email: "adriane.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "23478", type: "CRM" },
    status: "INACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "111",
    displayName: "ALF RODRIGUES NOGUEIRA",
    email: "alfrodriguesnogueira@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "16932", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "23",
    displayName: "AMELINA VERAZEZ SAMPAIO OLIVEIRA",
    email: "amelinaverazezsampai@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "18400", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "102",
    displayName: "Ana Carolina Andrade",
    email: "anacarolina.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: null, type: null },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: false, canManage: false },
  },
  {
    legacyId: "81",
    displayName: "ANA LUIZA COTLINSKI",
    email: "analuizacotlinski@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "46771", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "84",
    displayName: "ANA PAULA ROSA ISQUIERDO",
    email: "anapaularosaisquierd@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "248146", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "46",
    displayName: "ANDREA LAUGHTON DURANTE ATHAYDE",
    email: "andrealaughtondurant@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "17613", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "25",
    displayName: "ANTONIO EDUARDO DI PIETRO",
    email: "antonioeduardodipiet@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "15448", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "66",
    displayName: "BRUNA DE FREITAS BRAZZOLOTTO",
    email: "brunadefreitasbrazzo@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "353249", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "103",
    displayName: "CANNA SST",
    email: "cannasst@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "0026902", type: "PR" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: true, canSchedule: true, canManage: true },
  },
  {
    legacyId: "10",
    displayName: "CARMEN JAMUR",
    email: "carmenjamur@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "343800", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "11",
    displayName: "CARMEN MAYANNA JAMUR",
    email: "carmenmayannajamur@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "343800", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "93",
    displayName: "CAROLINA ALVIM PEREIRA",
    email: "carolinaalvimpereira@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "352837", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "12",
    displayName: "CAROLINA MONTEIRO CAMPOS",
    email: "carolinamonteirocamp@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "44198", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "30",
    displayName: "CAROLINE CLAUDINO DOS SANTOS",
    email: "carolineclaudino@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "29948", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "7",
    displayName: "CHARYSE ALICE MATTUELLA",
    email: "cris.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "27268", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "59",
    displayName: "CHARYSE ALICE MATTUELLA OTSUKA",
    email: "charysealicemattuell@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "27268", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "14",
    displayName: "Claudinei de Aguiar Dias",
    email: "claudinei.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "35325040", type: "MTE" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "89",
    displayName: "Cristiane P França",
    email: "cris.nxc@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: null, type: null },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "40",
    displayName: "DANILO CAMPOS MASCARENHAS LOPES",
    email: "danilocamposmascaren@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "17068", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "39",
    displayName: "DR. DANILO C.M LOPES",
    email: "danilo.lopes@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "17068", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "64",
    displayName: "Dr. Eurico Carlos Pereira",
    email: "eurico.pereira@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "39743", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "60",
    displayName: "Dr. Jose Luiz Hanemann de Campos",
    email: "joseluiz.campos@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "3333", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "31",
    displayName: "EDNA ALMEIDA E SILVA",
    email: "ednaalmeidaesilva@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "27934", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "15",
    displayName: "Eduardo da Silva Neto",
    email: "eduardo.neto@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "21299", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "33",
    displayName: "EDUARDO DE SOUZA BRITO GARCIA",
    email: "eduardo.garcia@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "60026", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "41",
    displayName: "EDUARDO MORIOKA BRESSANIM",
    email: "eduardomoriokabressa@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "350907", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "13",
    displayName: "ELOISE FORNAROLI",
    email: "eloisefornaroli@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "23839", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "3",
    displayName: "FELIPE CONEGLIAN DELLA BIANCA",
    email: "felipe.bianca@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: null, type: "CREA" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "53",
    displayName: "FERNANDA GONSALVES KUSTER",
    email: "fernandagonsalveskus@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "49964", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "109",
    displayName: "FRANCISO C.M QUINTANA",
    email: "francisco.quintana@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "54.611", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "86",
    displayName: "FRANCO WOLFF GODOY",
    email: "francowolffgodoy@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "312970", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "52",
    displayName: "GABRIELA REBECCA HACK",
    email: "gabrielarebeccahack@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "546313", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "76",
    displayName: "GABRIELA TULIO STRUCK",
    email: "gabrielatuliostruck@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "953351", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "98",
    displayName: "GIOVANNA GADELHA PEREIRA",
    email: "giovannagadelhaperei@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "856929", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "51",
    displayName: "GLAUCIO FERREIRA DE ARAUJO",
    email: "glaucioferreiradeara@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "2427927", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "79",
    displayName: "HENRIQUE LEONARDO RUCHAUD CORREA",
    email: "henriqueleonardoruch@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "6952700", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "78",
    displayName: "HENRIQUE TRIGO BIANCHESSI",
    email: "henriquetrigobianche@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "4095422", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "56",
    displayName: "HIL HOMEM OLIVEIRA DA COSTA",
    email: "hilhomemoliveiradaco@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "88940", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "62",
    displayName: "HUGO HENRIQUE NASCIMENTO",
    email: "hugo.nascimento@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "1709024917", type: "CREA" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "45",
    displayName: "IGOR DE MELLO PORCIUNCULA",
    email: "igordemelloporciuncu@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "28759", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "50",
    displayName: "ILKA MARI IKEBUTI TOYAMA",
    email: "ilkamariikebutitoyam@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "38801", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "54",
    displayName: "ISABEL DE OLIVEIRA",
    email: "isabeldeoliveira@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "751517", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "91",
    displayName: "JACKELINE STIEGLITZ CHIMICOVIAKI",
    email: "jackelinestieglitzch@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "754729", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "29",
    displayName: "Janaina Batista Rodrigues do Vale",
    email: "janaina.vale@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "1330D", type: "CREA" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "85",
    displayName: "JOSÉ KALIL NASSAR",
    email: "josékalilnassar@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "2769787", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "58",
    displayName: "JULIA DE MATTOS FETEIRA",
    email: "juliademattosfeteira@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "1187171", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "92",
    displayName: "JULIA MARIA RODRIGUES DA ROCHA",
    email: "juliamariarodriguesd@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "954843", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "28",
    displayName: "KAMILA MAYER DE PAULA",
    email: "kamila.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "14.8586", type: "CREA" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "38",
    displayName: "KARIN RINK",
    email: "karin.rink@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "65931-2", type: "CAU" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "82",
    displayName: "KASUTOSHI EDSON IZUMI",
    email: "kasutoshiedsonizumi@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "911512", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "20",
    displayName: "KAUAN FORMENTÃO",
    email: "kauanformentão@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "23241192", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "70",
    displayName: "LAURA ZATTAR OLIVEIRA",
    email: "laurazattaroliveira@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "648160", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "32",
    displayName: "LEANDRO DA SILVEIRA MEDEIROS",
    email: "leandro.medeiros@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "0025981", type: "MTE" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "42",
    displayName: "Lucineia Disner Heidemann Macedo",
    email: "lucineia.macedo@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "0014164", type: "MTE" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "9",
    displayName: "LUIZ CARLOS GUEDES RIBEIRO",
    email: "luizcarlosguedesribe@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "913001", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "88",
    displayName: "MARCELLA LUCIANO DE OLIVEIRA",
    email: "marcellalucianodeoli@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "1797981", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "77",
    displayName: "MARCELO VOLPE COELHO",
    email: "marcelovolpecoelho@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "18535089", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "61",
    displayName: "MARCO AURELIO DOS SANTOS",
    email: "marcoaureliodossanto@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "8316244", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "57",
    displayName: "MARIANA BITENCURT LISTON",
    email: "marianabitencurtlist@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "17551298", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "16",
    displayName: "MARIZA LEITZKE MATTOS",
    email: "marizaleitzkemattos@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "20610534", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "34",
    displayName: "MATHEUS S. FREDERICO",
    email: "matheus.frederico@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "48756", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "18",
    displayName: "MEIERSON REQUE",
    email: "meiersonreque@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "25611378", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "96",
    displayName: "MIGUEL LUIZ CARLET",
    email: "miguelluizcarlet@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "0978173", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "44",
    displayName: "MUSTAFA MAHMOUD DARWICHE",
    email: "mustafamahmouddarwic@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "34350938", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "80",
    displayName: "NICOLLE LOUISE GONÇALVES SOUZA E SILVA",
    email: "nicollelouisegonçalv@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "85051490", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "22",
    displayName: "PATRICIA DEL CORONA BRAGA CAVALCANTI",
    email: "patriciadelcoronabra@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "040145667", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "27",
    displayName: "PEDRO ALCIDES FELIPES",
    email: "pedroalcidesfelipes@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "41541530", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "5",
    displayName: "Roberto Sgrott da Silva",
    email: "roberto.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "53738", type: "CREA" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "17",
    displayName: "ROGER CATUNDA ROCHA",
    email: "rogercatundarocha@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "23697", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "101",
    displayName: "Roger Catunda Rocha (Noemi)",
    email: "noemialvesdepaula@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "254418", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "37",
    displayName: "SILVIO GABRIEL DE SOUZA PORCELI",
    email: "silvio.porceli@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "122368D", type: "CREA" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "69",
    displayName: "Stefanie Suzan Paulista",
    email: "stefanie.paulista@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: null, type: null },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "75",
    displayName: "TALISSA NAKADA GARDIN",
    email: "talissanakadagardin@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "27852303", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "24",
    displayName: "THAIS LIVON SAMPAIO",
    email: "thaislivonsampaio@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "869196648", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "19",
    displayName: "THAMIRES",
    email: "thamires.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "1412544", type: "COREN" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: true, canSchedule: true, canManage: false },
  },
  {
    legacyId: "95",
    displayName: "Thays Izadora Bortoloso da Silva",
    email: "thays.silva@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "28471", type: "MTE" },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "71",
    displayName: "THELMA ELISA AUFFINGER PEDROLLO",
    email: "thelmaelisaauffinger@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "95925454", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "74",
    displayName: "VALKER ANTONIO CORREA",
    email: "valkerantoniocorrea@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "144533259", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "94",
    displayName: "VANESSA CRISTINE GRAEFF",
    email: "vanessacristinegraef@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "585355213", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
  {
    legacyId: "26",
    displayName: "WEBSERVICE - INTEGRACAO",
    email: "meusoc.nextcon@prestador.nai.com.br",
    role: "SYSTEM_INTEGRATION",
    professionalId: { number: null, type: null },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: false, canManage: false },
  },
  {
    legacyId: "65",
    displayName: "Wellinson dos Sntos Barros",
    email: "wel.nextcon@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: null, type: null },
    status: "ACTIVE",
    permissions: { canIssueASO: false, canExam: false, canSchedule: true, canManage: false },
  },
  {
    legacyId: "72",
    displayName: "WILLIAM KUTNEY CARDOSO",
    email: "williamkutneycardoso@prestador.nai.com.br",
    role: "PROVIDER",
    professionalId: { number: "63753411", type: "CRM" },
    status: "ACTIVE",
    permissions: { canIssueASO: true, canExam: true, canSchedule: false, canManage: false },
  },
];
